version = "1.0"

[metadata]
author_name = "unknown"
author_email = "pash@cline.bot"
difficulty = "easy"
category = "software_engineering"
tags = [ "python", "postgresql", "psycopg2", "cursor-compatibility", "keyerror", "discord-bot", "real-world-task", "cline", "clinebench",]
custom_docker_compose = true

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
